// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: events.proto

package kitchenpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventStream_StreamKitchenEvents_FullMethodName = "/appetite.kitchen.v1.EventStream/StreamKitchenEvents"
	EventStream_StreamOrderEvents_FullMethodName   = "/appetite.kitchen.v1.EventStream/StreamOrderEvents"
)

// EventStreamClient is the client API for EventStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for streaming real-time events to web clients
type EventStreamClient interface {
	// Stream kitchen ticket events (created, status changes)
	StreamKitchenEvents(ctx context.Context, in *SubscribeKitchenEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KitchenTicketEvent], error)
	// Stream order item events (status changes, deliveries)
	StreamOrderEvents(ctx context.Context, in *SubscribeOrderEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderItemEvent], error)
}

type eventStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStreamClient(cc grpc.ClientConnInterface) EventStreamClient {
	return &eventStreamClient{cc}
}

func (c *eventStreamClient) StreamKitchenEvents(ctx context.Context, in *SubscribeKitchenEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KitchenTicketEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStream_ServiceDesc.Streams[0], EventStream_StreamKitchenEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeKitchenEventsRequest, KitchenTicketEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStream_StreamKitchenEventsClient = grpc.ServerStreamingClient[KitchenTicketEvent]

func (c *eventStreamClient) StreamOrderEvents(ctx context.Context, in *SubscribeOrderEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderItemEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStream_ServiceDesc.Streams[1], EventStream_StreamOrderEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeOrderEventsRequest, OrderItemEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStream_StreamOrderEventsClient = grpc.ServerStreamingClient[OrderItemEvent]

// EventStreamServer is the server API for EventStream service.
// All implementations must embed UnimplementedEventStreamServer
// for forward compatibility.
//
// Service for streaming real-time events to web clients
type EventStreamServer interface {
	// Stream kitchen ticket events (created, status changes)
	StreamKitchenEvents(*SubscribeKitchenEventsRequest, grpc.ServerStreamingServer[KitchenTicketEvent]) error
	// Stream order item events (status changes, deliveries)
	StreamOrderEvents(*SubscribeOrderEventsRequest, grpc.ServerStreamingServer[OrderItemEvent]) error
	mustEmbedUnimplementedEventStreamServer()
}

// UnimplementedEventStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStreamServer struct{}

func (UnimplementedEventStreamServer) StreamKitchenEvents(*SubscribeKitchenEventsRequest, grpc.ServerStreamingServer[KitchenTicketEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamKitchenEvents not implemented")
}
func (UnimplementedEventStreamServer) StreamOrderEvents(*SubscribeOrderEventsRequest, grpc.ServerStreamingServer[OrderItemEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrderEvents not implemented")
}
func (UnimplementedEventStreamServer) mustEmbedUnimplementedEventStreamServer() {}
func (UnimplementedEventStreamServer) testEmbeddedByValue()                     {}

// UnsafeEventStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStreamServer will
// result in compilation errors.
type UnsafeEventStreamServer interface {
	mustEmbedUnimplementedEventStreamServer()
}

func RegisterEventStreamServer(s grpc.ServiceRegistrar, srv EventStreamServer) {
	// If the following call pancis, it indicates UnimplementedEventStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStream_ServiceDesc, srv)
}

func _EventStream_StreamKitchenEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeKitchenEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStreamServer).StreamKitchenEvents(m, &grpc.GenericServerStream[SubscribeKitchenEventsRequest, KitchenTicketEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStream_StreamKitchenEventsServer = grpc.ServerStreamingServer[KitchenTicketEvent]

func _EventStream_StreamOrderEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeOrderEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStreamServer).StreamOrderEvents(m, &grpc.GenericServerStream[SubscribeOrderEventsRequest, OrderItemEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStream_StreamOrderEventsServer = grpc.ServerStreamingServer[OrderItemEvent]

// EventStream_ServiceDesc is the grpc.ServiceDesc for EventStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appetite.kitchen.v1.EventStream",
	HandlerType: (*EventStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamKitchenEvents",
			Handler:       _EventStream_StreamKitchenEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrderEvents",
			Handler:       _EventStream_StreamOrderEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "events.proto",
}
