coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%

fixes:
  - "github.com/appetiteclub/appetite/::"

ignore:
  - "**/demo.go"
  - "**/demo_test.go"
  - "**/proto/**"
  - "cmd/utils/**"
