// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/orderstream/proto/events.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to subscribe to order item events
type SubscribeOrderItemEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by table_id
	TableId string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Optional filter by order_id
	OrderId       string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOrderItemEventsRequest) Reset() {
	*x = SubscribeOrderItemEventsRequest{}
	mi := &file_internal_orderstream_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrderItemEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrderItemEventsRequest) ProtoMessage() {}

func (x *SubscribeOrderItemEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_orderstream_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrderItemEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeOrderItemEventsRequest) Descriptor() ([]byte, []int) {
	return file_internal_orderstream_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeOrderItemEventsRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *SubscribeOrderItemEventsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Order item event streamed to clients
type OrderItemEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type: "order.item.status_changed", "order.item.delivered", etc.
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// When the event occurred
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Order item identifiers
	OrderItemId string `protobuf:"bytes,3,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id,omitempty"`
	OrderId     string `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MenuItemId  string `protobuf:"bytes,5,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	// Display data
	DishName    string `protobuf:"bytes,6,opt,name=dish_name,json=dishName,proto3" json:"dish_name,omitempty"`
	Category    string `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	TableNumber string `protobuf:"bytes,8,opt,name=table_number,json=tableNumber,proto3" json:"table_number,omitempty"`
	// Status information
	NewStatus          string  `protobuf:"bytes,9,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	PreviousStatus     string  `protobuf:"bytes,10,opt,name=previous_status,json=previousStatus,proto3" json:"previous_status,omitempty"`
	Quantity           int32   `protobuf:"varint,11,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price              float64 `protobuf:"fixed64,12,opt,name=price,proto3" json:"price,omitempty"`
	RequiresProduction bool    `protobuf:"varint,13,opt,name=requires_production,json=requiresProduction,proto3" json:"requires_production,omitempty"`
	Notes              string  `protobuf:"bytes,14,opt,name=notes,proto3" json:"notes,omitempty"`
	// Timestamps
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemEvent) Reset() {
	*x = OrderItemEvent{}
	mi := &file_internal_orderstream_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemEvent) ProtoMessage() {}

func (x *OrderItemEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_orderstream_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemEvent.ProtoReflect.Descriptor instead.
func (*OrderItemEvent) Descriptor() ([]byte, []int) {
	return file_internal_orderstream_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItemEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OrderItemEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *OrderItemEvent) GetOrderItemId() string {
	if x != nil {
		return x.OrderItemId
	}
	return ""
}

func (x *OrderItemEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderItemEvent) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *OrderItemEvent) GetDishName() string {
	if x != nil {
		return x.DishName
	}
	return ""
}

func (x *OrderItemEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *OrderItemEvent) GetTableNumber() string {
	if x != nil {
		return x.TableNumber
	}
	return ""
}

func (x *OrderItemEvent) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *OrderItemEvent) GetPreviousStatus() string {
	if x != nil {
		return x.PreviousStatus
	}
	return ""
}

func (x *OrderItemEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemEvent) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItemEvent) GetRequiresProduction() bool {
	if x != nil {
		return x.RequiresProduction
	}
	return false
}

func (x *OrderItemEvent) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *OrderItemEvent) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

var File_internal_orderstream_proto_events_proto protoreflect.FileDescriptor

const file_internal_orderstream_proto_events_proto_rawDesc = "" +
	"\n" +
	"'internal/orderstream/proto/events.proto\x12\x11appetite.order.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\x1fSubscribeOrderItemEventsRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\xa9\x04\n" +
	"\x0eOrderItemEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\"\n" +
	"\rorder_item_id\x18\x03 \x01(\tR\vorderItemId\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12 \n" +
	"\fmenu_item_id\x18\x05 \x01(\tR\n" +
	"menuItemId\x12\x1b\n" +
	"\tdish_name\x18\x06 \x01(\tR\bdishName\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12!\n" +
	"\ftable_number\x18\b \x01(\tR\vtableNumber\x12\x1d\n" +
	"\n" +
	"new_status\x18\t \x01(\tR\tnewStatus\x12'\n" +
	"\x0fprevious_status\x18\n" +
	" \x01(\tR\x0epreviousStatus\x12\x1a\n" +
	"\bquantity\x18\v \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\f \x01(\x01R\x05price\x12/\n" +
	"\x13requires_production\x18\r \x01(\bR\x12requiresProduction\x12\x14\n" +
	"\x05notes\x18\x0e \x01(\tR\x05notes\x12=\n" +
	"\fdelivered_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt2\x84\x01\n" +
	"\x10OrderEventStream\x12p\n" +
	"\x15StreamOrderItemEvents\x122.appetite.order.v1.SubscribeOrderItemEventsRequest\x1a!.appetite.order.v1.OrderItemEvent0\x01BYZWgithub.com/appetiteclub/appetite/services/operations/internal/orderstream/proto;orderpbb\x06proto3"

var (
	file_internal_orderstream_proto_events_proto_rawDescOnce sync.Once
	file_internal_orderstream_proto_events_proto_rawDescData []byte
)

func file_internal_orderstream_proto_events_proto_rawDescGZIP() []byte {
	file_internal_orderstream_proto_events_proto_rawDescOnce.Do(func() {
		file_internal_orderstream_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_orderstream_proto_events_proto_rawDesc), len(file_internal_orderstream_proto_events_proto_rawDesc)))
	})
	return file_internal_orderstream_proto_events_proto_rawDescData
}

var file_internal_orderstream_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_orderstream_proto_events_proto_goTypes = []any{
	(*SubscribeOrderItemEventsRequest)(nil), // 0: appetite.order.v1.SubscribeOrderItemEventsRequest
	(*OrderItemEvent)(nil),                  // 1: appetite.order.v1.OrderItemEvent
	(*timestamppb.Timestamp)(nil),           // 2: google.protobuf.Timestamp
}
var file_internal_orderstream_proto_events_proto_depIdxs = []int32{
	2, // 0: appetite.order.v1.OrderItemEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2, // 1: appetite.order.v1.OrderItemEvent.delivered_at:type_name -> google.protobuf.Timestamp
	0, // 2: appetite.order.v1.OrderEventStream.StreamOrderItemEvents:input_type -> appetite.order.v1.SubscribeOrderItemEventsRequest
	1, // 3: appetite.order.v1.OrderEventStream.StreamOrderItemEvents:output_type -> appetite.order.v1.OrderItemEvent
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_orderstream_proto_events_proto_init() }
func file_internal_orderstream_proto_events_proto_init() {
	if File_internal_orderstream_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_orderstream_proto_events_proto_rawDesc), len(file_internal_orderstream_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_orderstream_proto_events_proto_goTypes,
		DependencyIndexes: file_internal_orderstream_proto_events_proto_depIdxs,
		MessageInfos:      file_internal_orderstream_proto_events_proto_msgTypes,
	}.Build()
	File_internal_orderstream_proto_events_proto = out.File
	file_internal_orderstream_proto_events_proto_goTypes = nil
	file_internal_orderstream_proto_events_proto_depIdxs = nil
}
