// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: events.proto

package kitchenpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to subscribe to kitchen events
type SubscribeKitchenEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by station_id
	StationId     string `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeKitchenEventsRequest) Reset() {
	*x = SubscribeKitchenEventsRequest{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeKitchenEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeKitchenEventsRequest) ProtoMessage() {}

func (x *SubscribeKitchenEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeKitchenEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeKitchenEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeKitchenEventsRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

// Kitchen ticket event streamed to clients
type KitchenTicketEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type: "kitchen.ticket.created" or "kitchen.ticket.status_changed"
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// When the event occurred
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Ticket identifiers
	TicketId    string `protobuf:"bytes,3,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	OrderId     string `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderItemId string `protobuf:"bytes,5,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id,omitempty"`
	MenuItemId  string `protobuf:"bytes,6,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	StationId   string `protobuf:"bytes,7,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	// Denormalized display data
	MenuItemName string `protobuf:"bytes,8,opt,name=menu_item_name,json=menuItemName,proto3" json:"menu_item_name,omitempty"`
	StationName  string `protobuf:"bytes,9,opt,name=station_name,json=stationName,proto3" json:"station_name,omitempty"`
	TableNumber  string `protobuf:"bytes,10,opt,name=table_number,json=tableNumber,proto3" json:"table_number,omitempty"`
	// Status information
	NewStatusId      string `protobuf:"bytes,11,opt,name=new_status_id,json=newStatusId,proto3" json:"new_status_id,omitempty"`
	PreviousStatusId string `protobuf:"bytes,12,opt,name=previous_status_id,json=previousStatusId,proto3" json:"previous_status_id,omitempty"`
	Quantity         int32  `protobuf:"varint,13,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Notes            string `protobuf:"bytes,14,opt,name=notes,proto3" json:"notes,omitempty"`
	// Timestamps
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KitchenTicketEvent) Reset() {
	*x = KitchenTicketEvent{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KitchenTicketEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenTicketEvent) ProtoMessage() {}

func (x *KitchenTicketEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenTicketEvent.ProtoReflect.Descriptor instead.
func (*KitchenTicketEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *KitchenTicketEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *KitchenTicketEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *KitchenTicketEvent) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *KitchenTicketEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *KitchenTicketEvent) GetOrderItemId() string {
	if x != nil {
		return x.OrderItemId
	}
	return ""
}

func (x *KitchenTicketEvent) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *KitchenTicketEvent) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *KitchenTicketEvent) GetMenuItemName() string {
	if x != nil {
		return x.MenuItemName
	}
	return ""
}

func (x *KitchenTicketEvent) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

func (x *KitchenTicketEvent) GetTableNumber() string {
	if x != nil {
		return x.TableNumber
	}
	return ""
}

func (x *KitchenTicketEvent) GetNewStatusId() string {
	if x != nil {
		return x.NewStatusId
	}
	return ""
}

func (x *KitchenTicketEvent) GetPreviousStatusId() string {
	if x != nil {
		return x.PreviousStatusId
	}
	return ""
}

func (x *KitchenTicketEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *KitchenTicketEvent) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *KitchenTicketEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *KitchenTicketEvent) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *KitchenTicketEvent) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

// Request to subscribe to order events
type SubscribeOrderEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by table_id or order_id
	TableId       string `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	OrderId       string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOrderEventsRequest) Reset() {
	*x = SubscribeOrderEventsRequest{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrderEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrderEventsRequest) ProtoMessage() {}

func (x *SubscribeOrderEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrderEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeOrderEventsRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeOrderEventsRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *SubscribeOrderEventsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Order item event streamed to clients
type OrderItemEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// When the event occurred
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Order item identifiers
	OrderItemId string `protobuf:"bytes,3,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id,omitempty"`
	OrderId     string `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DishId      string `protobuf:"bytes,5,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	// Display data
	DishName    string `protobuf:"bytes,6,opt,name=dish_name,json=dishName,proto3" json:"dish_name,omitempty"`
	TableNumber string `protobuf:"bytes,7,opt,name=table_number,json=tableNumber,proto3" json:"table_number,omitempty"`
	// Status information
	NewStatus          string `protobuf:"bytes,8,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	PreviousStatus     string `protobuf:"bytes,9,opt,name=previous_status,json=previousStatus,proto3" json:"previous_status,omitempty"`
	Quantity           int32  `protobuf:"varint,10,opt,name=quantity,proto3" json:"quantity,omitempty"`
	RequiresProduction bool   `protobuf:"varint,11,opt,name=requires_production,json=requiresProduction,proto3" json:"requires_production,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderItemEvent) Reset() {
	*x = OrderItemEvent{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemEvent) ProtoMessage() {}

func (x *OrderItemEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemEvent.ProtoReflect.Descriptor instead.
func (*OrderItemEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *OrderItemEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OrderItemEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *OrderItemEvent) GetOrderItemId() string {
	if x != nil {
		return x.OrderItemId
	}
	return ""
}

func (x *OrderItemEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderItemEvent) GetDishId() string {
	if x != nil {
		return x.DishId
	}
	return ""
}

func (x *OrderItemEvent) GetDishName() string {
	if x != nil {
		return x.DishName
	}
	return ""
}

func (x *OrderItemEvent) GetTableNumber() string {
	if x != nil {
		return x.TableNumber
	}
	return ""
}

func (x *OrderItemEvent) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *OrderItemEvent) GetPreviousStatus() string {
	if x != nil {
		return x.PreviousStatus
	}
	return ""
}

func (x *OrderItemEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemEvent) GetRequiresProduction() bool {
	if x != nil {
		return x.RequiresProduction
	}
	return false
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x13appetite.kitchen.v1\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x1dSubscribeKitchenEventsRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\"\xb4\x05\n" +
	"\x12KitchenTicketEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1b\n" +
	"\tticket_id\x18\x03 \x01(\tR\bticketId\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12\"\n" +
	"\rorder_item_id\x18\x05 \x01(\tR\vorderItemId\x12 \n" +
	"\fmenu_item_id\x18\x06 \x01(\tR\n" +
	"menuItemId\x12\x1d\n" +
	"\n" +
	"station_id\x18\a \x01(\tR\tstationId\x12$\n" +
	"\x0emenu_item_name\x18\b \x01(\tR\fmenuItemName\x12!\n" +
	"\fstation_name\x18\t \x01(\tR\vstationName\x12!\n" +
	"\ftable_number\x18\n" +
	" \x01(\tR\vtableNumber\x12\"\n" +
	"\rnew_status_id\x18\v \x01(\tR\vnewStatusId\x12,\n" +
	"\x12previous_status_id\x18\f \x01(\tR\x10previousStatusId\x12\x1a\n" +
	"\bquantity\x18\r \x01(\x05R\bquantity\x12\x14\n" +
	"\x05notes\x18\x0e \x01(\tR\x05notes\x129\n" +
	"\n" +
	"started_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12=\n" +
	"\fdelivered_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\"S\n" +
	"\x1bSubscribeOrderEventsRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\x99\x03\n" +
	"\x0eOrderItemEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\"\n" +
	"\rorder_item_id\x18\x03 \x01(\tR\vorderItemId\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12\x17\n" +
	"\adish_id\x18\x05 \x01(\tR\x06dishId\x12\x1b\n" +
	"\tdish_name\x18\x06 \x01(\tR\bdishName\x12!\n" +
	"\ftable_number\x18\a \x01(\tR\vtableNumber\x12\x1d\n" +
	"\n" +
	"new_status\x18\b \x01(\tR\tnewStatus\x12'\n" +
	"\x0fprevious_status\x18\t \x01(\tR\x0epreviousStatus\x12\x1a\n" +
	"\bquantity\x18\n" +
	" \x01(\x05R\bquantity\x12/\n" +
	"\x13requires_production\x18\v \x01(\bR\x12requiresProduction2\xf1\x01\n" +
	"\vEventStream\x12t\n" +
	"\x13StreamKitchenEvents\x122.appetite.kitchen.v1.SubscribeKitchenEventsRequest\x1a'.appetite.kitchen.v1.KitchenTicketEvent0\x01\x12l\n" +
	"\x11StreamOrderEvents\x120.appetite.kitchen.v1.SubscribeOrderEventsRequest\x1a#.appetite.kitchen.v1.OrderItemEvent0\x01BTZRgithub.com/appetiteclub/appetite/services/kitchen/internal/kitchen/proto;kitchenpbb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_events_proto_goTypes = []any{
	(*SubscribeKitchenEventsRequest)(nil), // 0: appetite.kitchen.v1.SubscribeKitchenEventsRequest
	(*KitchenTicketEvent)(nil),            // 1: appetite.kitchen.v1.KitchenTicketEvent
	(*SubscribeOrderEventsRequest)(nil),   // 2: appetite.kitchen.v1.SubscribeOrderEventsRequest
	(*OrderItemEvent)(nil),                // 3: appetite.kitchen.v1.OrderItemEvent
	(*timestamppb.Timestamp)(nil),         // 4: google.protobuf.Timestamp
}
var file_events_proto_depIdxs = []int32{
	4, // 0: appetite.kitchen.v1.KitchenTicketEvent.occurred_at:type_name -> google.protobuf.Timestamp
	4, // 1: appetite.kitchen.v1.KitchenTicketEvent.started_at:type_name -> google.protobuf.Timestamp
	4, // 2: appetite.kitchen.v1.KitchenTicketEvent.finished_at:type_name -> google.protobuf.Timestamp
	4, // 3: appetite.kitchen.v1.KitchenTicketEvent.delivered_at:type_name -> google.protobuf.Timestamp
	4, // 4: appetite.kitchen.v1.OrderItemEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 5: appetite.kitchen.v1.EventStream.StreamKitchenEvents:input_type -> appetite.kitchen.v1.SubscribeKitchenEventsRequest
	2, // 6: appetite.kitchen.v1.EventStream.StreamOrderEvents:input_type -> appetite.kitchen.v1.SubscribeOrderEventsRequest
	1, // 7: appetite.kitchen.v1.EventStream.StreamKitchenEvents:output_type -> appetite.kitchen.v1.KitchenTicketEvent
	3, // 8: appetite.kitchen.v1.EventStream.StreamOrderEvents:output_type -> appetite.kitchen.v1.OrderItemEvent
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
