// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: internal/order/proto/events.proto

package orderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderEventStream_StreamOrderItemEvents_FullMethodName = "/appetite.order.v1.OrderEventStream/StreamOrderItemEvents"
)

// OrderEventStreamClient is the client API for OrderEventStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for streaming real-time order item events to clients
type OrderEventStreamClient interface {
	// Stream order item events (status changes, deliveries, cancellations)
	StreamOrderItemEvents(ctx context.Context, in *SubscribeOrderItemEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderItemEvent], error)
}

type orderEventStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderEventStreamClient(cc grpc.ClientConnInterface) OrderEventStreamClient {
	return &orderEventStreamClient{cc}
}

func (c *orderEventStreamClient) StreamOrderItemEvents(ctx context.Context, in *SubscribeOrderItemEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderItemEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderEventStream_ServiceDesc.Streams[0], OrderEventStream_StreamOrderItemEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeOrderItemEventsRequest, OrderItemEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderEventStream_StreamOrderItemEventsClient = grpc.ServerStreamingClient[OrderItemEvent]

// OrderEventStreamServer is the server API for OrderEventStream service.
// All implementations must embed UnimplementedOrderEventStreamServer
// for forward compatibility.
//
// Service for streaming real-time order item events to clients
type OrderEventStreamServer interface {
	// Stream order item events (status changes, deliveries, cancellations)
	StreamOrderItemEvents(*SubscribeOrderItemEventsRequest, grpc.ServerStreamingServer[OrderItemEvent]) error
	mustEmbedUnimplementedOrderEventStreamServer()
}

// UnimplementedOrderEventStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderEventStreamServer struct{}

func (UnimplementedOrderEventStreamServer) StreamOrderItemEvents(*SubscribeOrderItemEventsRequest, grpc.ServerStreamingServer[OrderItemEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrderItemEvents not implemented")
}
func (UnimplementedOrderEventStreamServer) mustEmbedUnimplementedOrderEventStreamServer() {}
func (UnimplementedOrderEventStreamServer) testEmbeddedByValue()                          {}

// UnsafeOrderEventStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderEventStreamServer will
// result in compilation errors.
type UnsafeOrderEventStreamServer interface {
	mustEmbedUnimplementedOrderEventStreamServer()
}

func RegisterOrderEventStreamServer(s grpc.ServiceRegistrar, srv OrderEventStreamServer) {
	// If the following call pancis, it indicates UnimplementedOrderEventStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderEventStream_ServiceDesc, srv)
}

func _OrderEventStream_StreamOrderItemEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeOrderItemEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderEventStreamServer).StreamOrderItemEvents(m, &grpc.GenericServerStream[SubscribeOrderItemEventsRequest, OrderItemEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderEventStream_StreamOrderItemEventsServer = grpc.ServerStreamingServer[OrderItemEvent]

// OrderEventStream_ServiceDesc is the grpc.ServiceDesc for OrderEventStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderEventStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appetite.order.v1.OrderEventStream",
	HandlerType: (*OrderEventStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOrderItemEvents",
			Handler:       _OrderEventStream_StreamOrderItemEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/order/proto/events.proto",
}
